
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 77
#define YY_END_OF_BUFFER 78
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[259] =
    {   0,
       52,   52,   78,   76,   51,   50,   76,   76,   55,   76,
       41,   42,   48,   53,   49,   54,   76,   56,   64,   47,
       57,   45,   58,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   51,   50,   50,
       50,    0,   32,    0,    0,    0,   52,    0,    0,    0,
        0,    0,   44,    0,   64,    0,   46,   59,   43,   60,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   27,
       63,   63,   63,   63,   63,   63,   20,   17,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       68,   69,    0,    0,    0,    0,    0,    0,    0,    0,

       65,    0,   66,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,    6,   63,   63,   63,   63,   63,   39,
       14,   63,   18,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,    0,    0,    0,    0,    0,    0,   36,
        0,   67,   63,   29,   25,   63,   63,   63,   63,   63,
       63,   23,   30,   63,   38,   40,   63,   63,   63,   63,
        7,   63,   63,   63,   63,   21,   15,   63,   73,    0,
        0,    0,   35,    0,    0,   34,    0,   67,   63,   63,
       63,   63,   31,   63,   63,   63,   63,   63,   63,   63,
       19,   63,   63,   63,   63,   63,   28,    0,    0,    0,

        0,    0,   37,   61,   63,   63,   63,   63,   63,   63,
       22,   63,   63,   16,   63,   63,    4,   24,   63,   33,
       72,   71,    0,    0,   62,   63,   63,    9,   63,   26,
       63,   63,    8,   11,    1,   63,    0,    0,   63,   63,
        5,   63,    3,   63,   70,    0,   63,   10,   12,   63,
       75,    0,   63,    2,   74,    0,   13,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    7,    8,    1,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,    7,   21,
       22,   23,    7,    7,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   33,
        7,    1,    7,    7,   48,    7,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   33,   33,   58,   59,   60,
       61,   62,   63,   64,   65,   66,   67,   68,   69,   70,
       71,   33,    7,   72,    7,    7,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[73] =
    {   0,
        1,    1,    1,    2,    2,    1,    2,    2,    2,    2,
        2,    2,    2,    1,    2,    2,    1,    3,    3,    2,
        2,    2,    2,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    2
    } ;

static const flex_int16_t yy_base[264] =
    {   0,
        0,    0,  430, 1126,   71,   74,  425,    0, 1126,    0,
       61, 1126,  410, 1126, 1126, 1126,   57,  398,   69,  379,
      371,  368,  352,   71,   64,  124,   96,  116,   73,  178,
      140,   84,   90,  151,  192,  194,  198,  143,  163,  179,
      187,  361, 1126,  342,  336,   82,  319,   71,   71,  147,
       73,   96, 1126,  107,  205,  234, 1126, 1126, 1126, 1126,
        0,  200,  237,  245,  248,  256,  225,  251,  263,  265,
      271,  282,  289,  299,  305,  307,  309,  314,  321,  324,
      333,  331,  357,  359,  348,  373,  383,  385,  391,  393,
     1126,  320,  269,  352,  151,  105,  159,  194,  304,  235,

      408,  368,  398,  418,  424,  428,  430,  426,  443,  449,
      468,  471,  477,  483,  485,  492,  494,  496,  504,  510,
      516,  529,  519,  535,  544,  531,  537,  550,  554,  563,
      572,  569,  582,  596,  607,  278,  273,  351,  252, 1126,
      177,  244,  605,  591,  609,  617,  624,  626,  633,  628,
      644,  636,  619,  659,  651,  669,  672,  687,  691,  678,
      693,  696,  705,  703,  710,  727,  729,  731, 1126,  433,
      557,  340, 1126,  181,  241, 1126,  212, 1126,  744,  747,
      752,  764,  767,  769,  772,  790,  792,  788,  804,  807,
      810,  815,  824,  829,  832,  850,  835,  783,  868,  630,

      178,  140, 1126, 1126,  843,  855,  870,  874,  882,  893,
      889,  895,  909,  917,  920,  926,  928,  933,  940,  944,
     1126, 1126,  841,  886, 1126,  948,  951,  965,  968,  971,
      975,  982,  984,  989,  992,  996, 1006,  901, 1002, 1016,
     1020, 1027, 1029, 1036, 1126, 1040, 1042, 1047, 1051, 1055,
     1126,  176, 1063, 1067, 1126,   99, 1070, 1126, 1118, 1120,
     1122,  101,   81
    } ;

static const flex_int16_t yy_def[264] =
    {   0,
      258,    1,  258,  258,  258,  258,  259,  260,  258,  261,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  258,  258,  258,
      258,  259,  258,  260,  261,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      263,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      258,  261,  258,  258,  258,  258,  258,  258,  258,  258,

      258,  258,  258,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  258,  258,  258,

      258,  258,  258,  258,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      258,  258,  258,  258,  258,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  258,  258,  262,  262,
      262,  262,  262,  262,  258,  258,  262,  262,  262,  262,
      258,  258,  262,  262,  258,  258,  262,    0,  258,  258,
      258,  258,  258
    } ;

static const flex_int16_t yy_nxt[1199] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   25,
       25,   30,   25,   31,   25,   25,   32,   33,   25,   34,
       35,   36,   25,   25,   37,   25,   25,    4,   24,   25,
       26,   27,   28,   29,   25,   25,   30,   31,   25,   25,
       32,   33,   25,   34,   35,   36,   25,   25,   37,   25,
       25,    4,   38,   39,   38,   40,   41,   40,   46,   46,
       48,   61,   61,   61,   54,   49,   55,   55,   61,   61,
       61,   61,   50,   51,   96,   93,   56,   94,   52,   46,

       46,   61,   61,   62,   63,   48,   95,   61,   61,  255,
       49,   61,   99,   61,   61,   74,   50,   51,   61,   96,
       61,   56,   52,   68,  101,  101,   82,   69,   63,   83,
       95,   61,   70,   61,   61,  100,   99,   61,  137,   74,
       56,   61,   61,   61,   38,   39,   38,   64,   68,   71,
       82,   72,   69,   83,   65,  225,   70,   61,   61,  100,
       66,   73,  137,   61,   40,   41,   40,   80,   61,   61,
       67,   61,   64,   71,   97,   72,   81,  136,   84,   65,
       40,   41,   40,   98,   66,   73,  255,   61,   40,   41,
       40,  200,   80,  256,   67,   61,   61,  138,   61,   97,

       81,   75,  136,   84,  177,   76,   77,   98,  202,   61,
       61,   61,   61,   78,   79,   61,   61,   61,   61,   85,
       54,  138,   55,   55,   88,   61,   75,  204,   90,  177,
       76,   77,   56,  202,   86,  139,   87,   78,   79,   61,
       89,   61,   61,   61,   85,   61,  102,   61,  102,   88,
      110,  103,  103,   90,   61,   61,  203,   56,   86,  139,
       87,  178,   61,   61,   89,   61,   61,  176,   61,   61,
      104,  107,   61,   61,   61,  110,   56,  141,  105,  111,
       61,   61,   61,   61,   61,  106,  134,  134,   61,   61,
      108,  109,   61,  173,  104,   61,  107,  112,   61,   61,

       61,  141,  105,   61,  111,  102,   61,   61,  114,  106,
       61,  113,   61,  174,  108,  109,   61,   61,   61,  140,
      115,  112,   61,   61,   61,   61,   61,   61,   92,   61,
       47,   61,   61,  114,  116,  113,   61,  174,   61,   61,
      117,   61,   61,  118,   92,  115,   61,   91,   61,   61,
       61,   61,   61,  200,   61,  119,   61,  201,  116,  121,
      120,   61,  122,   43,  117,   61,   61,  118,   61,  135,
      135,   61,  123,   60,   61,   61,   61,   61,   61,  119,
       61,  128,  126,  121,  120,  103,  103,  122,  124,   59,
       61,   61,   58,  125,  175,   61,  123,  129,   57,  127,

       61,   61,   61,   61,   61,  128,   61,  126,   61,   61,
       61,   61,  131,  124,  130,  103,  103,  125,  175,   53,
       61,   47,  129,  127,  133,  101,  101,   43,  132,  258,
       61,  258,   61,  258,  142,   61,   61,  131,   61,  130,
       61,   61,   61,   61,   61,   61,   61,   61,   61,  133,
      198,  198,  132,  258,  143,  145,  258,  144,  258,  142,
       61,   61,  258,  147,  258,   61,   61,   61,  258,  146,
      258,   61,  258,   61,  258,   61,  258,   61,  143,  142,
      145,  144,  149,  258,  148,   61,   61,  147,   61,   61,
       61,  150,  258,  146,   61,   61,   61,  258,  151,  258,

       61,   61,   61,   61,  152,  258,  149,  258,  148,   61,
       61,   61,   61,   61,   61,   61,  150,  154,   61,  258,
      155,   61,   61,  151,   61,  258,  153,   61,   61,  152,
       61,  157,   61,   61,   61,  156,   61,   61,  258,   61,
      258,   61,  154,   61,  258,  155,   61,   61,   61,   61,
      153,   61,   61,   61,   61,   61,  157,   61,  258,  156,
      158,   61,   61,   61,  161,  258,   61,   61,   61,  258,
      159,   61,   61,  160,  199,  199,   61,  163,   61,  162,
       61,   61,   61,  258,   61,  158,   61,   61,  161,   61,
       61,   61,  258,  164,  159,  258,  167,   61,  160,   61,

       61,   61,  163,  162,  165,  258,  169,  166,   61,   61,
       61,  170,  258,  134,  134,  168,   61,  164,  258,   61,
      171,  167,   61,   61,  135,  135,   61,   61,  165,   61,
      179,  166,  258,  172,   61,   61,   61,   61,   61,  168,
      180,   61,   61,   61,   61,   61,   61,  224,  224,  182,
       61,   61,   61,   61,   61,  179,   61,  181,  172,  258,
      183,   61,   61,  258,   61,  180,   61,  186,   61,   61,
      184,   61,  258,   61,  182,   61,   61,   61,  172,  185,
       61,  181,  258,   61,  258,  183,   61,   61,  258,   61,
       61,   61,  186,  258,  184,   61,   61,  258,   61,  258,

      187,  188,  258,  185,   61,   61,   61,  189,   61,   61,
       61,   61,  190,   61,   61,  258,   61,  192,  258,   61,
       61,   61,   61,   61,  187,   61,  188,   61,   61,  193,
      194,  189,  191,  258,   61,  196,  258,  190,   61,  195,
       61,  192,  258,   61,   61,   61,   61,   61,   61,   61,
       61,  258,   61,  193,  258,  194,  191,   61,  197,  258,
      196,   61,   61,  195,   61,   61,  258,  205,  258,   61,
       61,  258,  206,  258,   61,  258,   61,  258,   61,  207,
      258,   61,   61,  197,   61,   61,   61,   61,  258,   61,
       61,   61,  205,  221,   61,  208,  258,  206,  258,   61,

      198,  198,  209,  258,  207,   61,   61,   61,   61,   61,
       61,   61,  210,  258,   61,  213,   61,  258,  211,   61,
      208,   61,   61,  212,   61,   61,  209,   61,   61,  258,
      215,  258,   61,   61,  258,   61,  210,   61,  216,   61,
      213,   61,   61,  211,  258,  214,   61,   61,  212,   61,
       61,   61,   61,   61,   61,  215,  258,   61,  237,  237,
       61,   61,   61,  216,  258,  217,  258,   61,   61,  214,
      218,   61,   61,   61,  219,  258,   61,  258,  222,   61,
      220,  258,   61,  223,  226,  199,  199,   61,   61,  217,
       61,   61,   61,  258,  218,  258,  227,   61,  219,   61,

       61,  238,   61,  224,  224,  220,   61,   61,  226,  229,
       61,   61,   61,   61,  258,  228,  258,   61,  246,  246,
      227,   61,  258,  230,  231,  258,   61,   61,  258,   61,
      258,  232,  258,  229,   61,   61,   61,   61,   61,  228,
       61,  258,   61,   61,   61,   61,   61,  230,  233,  231,
       61,   61,  258,  234,  258,  232,   61,   61,   61,  258,
      235,   61,   61,  258,   61,   61,   61,   61,   61,   61,
      258,  239,  233,   61,  258,   61,  258,  234,  240,  258,
       61,  236,   61,   61,  235,   61,   61,   61,   61,   61,
      258,   61,   61,   61,  258,   61,  239,  258,   61,   61,

       61,   61,   61,  240,  258,  236,   61,   61,  241,   61,
       61,  242,   61,   61,   61,   61,  245,  243,   61,   61,
       61,  258,   61,  237,  237,  258,  247,  244,  258,   61,
      258,   61,  241,   61,   61,  242,   61,   61,   61,   61,
      258,  243,  258,   61,   61,   61,   61,   61,  258,   61,
      251,  247,  244,   61,   61,  248,  258,  246,  246,   61,
       61,  258,  249,   61,   61,   61,  252,   61,   61,   61,
      258,  250,   61,   61,   61,  253,   61,  258,  258,  248,
       61,   61,  254,   61,   61,   61,  249,   61,   61,   61,
      257,  252,  258,  258,   61,  250,  258,  258,   61,  253,

      258,  258,   61,  258,  258,  258,  258,  254,  258,  258,
       61,  252,  258,  258,   61,  257,  258,   61,   42,   42,
       42,   44,   44,   45,   45,    3,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258

    } ;

static const flex_int16_t yy_chk[1199] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    5,    5,    6,    6,    6,   11,   11,
       17,   25,   25,  263,   19,   17,   19,   19,   24,   24,
       29,   29,   17,   17,   49,   46,   19,   46,   17,   46,

       46,   32,   32,  262,   24,   17,   48,   33,   33,  256,
       17,   25,   51,   27,   27,   29,   17,   17,   24,   49,
       29,   19,   17,   27,   54,   54,   32,   27,   24,   33,
       48,   32,   27,   28,   28,   52,   51,   33,   96,   29,
       19,   26,   26,   27,   38,   38,   38,   26,   27,   28,
       32,   28,   27,   33,   26,  202,   27,   31,   31,   52,
       26,   28,   96,   28,   39,   39,   39,   31,   34,   34,
       26,   26,   26,   28,   50,   28,   31,   95,   34,   26,
       40,   40,   40,   50,   26,   28,  252,   31,   41,   41,
       41,  201,   31,  252,   26,   30,   30,   97,   34,   50,

       31,   30,   95,   34,  141,   30,   30,   50,  174,   35,
       35,   36,   36,   30,   30,   37,   37,   62,   62,   35,
       55,   97,   55,   55,   36,   30,   30,  177,   37,  141,
       30,   30,   55,  174,   35,   98,   35,   30,   30,   35,
       36,   36,   67,   67,   35,   37,   56,   62,   56,   36,
       67,   56,   56,   37,   63,   63,  175,   55,   35,   98,
       35,  142,   64,   64,   36,   65,   65,  139,   68,   68,
       63,   65,   67,   66,   66,   67,   55,  100,   64,   68,
       69,   69,   70,   70,   63,   64,   93,   93,   71,   71,
       66,   66,   64,  136,   63,   65,   65,   69,   68,   72,

       72,  100,   64,   66,   68,   56,   73,   73,   72,   64,
       69,   71,   70,  137,   66,   66,   74,   74,   71,   99,
       73,   69,   75,   75,   76,   76,   77,   77,   92,   72,
       47,   78,   78,   72,   74,   71,   73,  137,   79,   79,
       75,   80,   80,   76,   45,   73,   74,   44,   82,   82,
       81,   81,   75,  172,   76,   78,   77,  172,   74,   80,
       79,   78,   81,   42,   75,   85,   85,   76,   79,   94,
       94,   80,   82,   23,   83,   83,   84,   84,   82,   78,
       81,   85,   84,   80,   79,  102,  102,   81,   83,   22,
       86,   86,   21,   83,  138,   85,   82,   86,   20,   84,

       87,   87,   88,   88,   83,   85,   84,   84,   89,   89,
       90,   90,   88,   83,   87,  103,  103,   83,  138,   18,
       86,   13,   86,   84,   90,  101,  101,    7,   89,    3,
       87,    0,   88,    0,  101,  104,  104,   88,   89,   87,
       90,  105,  105,  108,  108,  106,  106,  107,  107,   90,
      170,  170,   89,    0,  104,  106,    0,  105,    0,  101,
      109,  109,    0,  108,    0,  104,  110,  110,    0,  107,
        0,  105,    0,  108,    0,  106,    0,  107,  104,  101,
      106,  105,  110,    0,  109,  111,  111,  108,  112,  112,
      109,  111,    0,  107,  113,  113,  110,    0,  112,    0,

      114,  114,  115,  115,  113,    0,  110,    0,  109,  116,
      116,  117,  117,  118,  118,  111,  111,  116,  112,    0,
      117,  119,  119,  112,  113,    0,  115,  120,  120,  113,
      114,  119,  115,  121,  121,  118,  123,  123,    0,  116,
        0,  117,  116,  118,    0,  117,  122,  122,  126,  126,
      115,  119,  124,  124,  127,  127,  119,  120,    0,  118,
      122,  125,  125,  121,  126,    0,  123,  128,  128,    0,
      124,  129,  129,  125,  171,  171,  122,  128,  126,  127,
      130,  130,  124,    0,  127,  122,  132,  132,  126,  131,
      131,  125,    0,  129,  124,    0,  132,  128,  125,  133,

      133,  129,  128,  127,  130,    0,  134,  131,  144,  144,
      130,  134,    0,  134,  134,  133,  132,  129,    0,  131,
      135,  132,  143,  143,  135,  135,  145,  145,  130,  133,
      143,  131,    0,  135,  146,  146,  153,  153,  144,  133,
      146,  147,  147,  148,  148,  150,  150,  200,  200,  148,
      149,  149,  143,  152,  152,  143,  145,  147,  135,    0,
      149,  151,  151,    0,  146,  146,  153,  152,  155,  155,
      150,  147,    0,  148,  148,  150,  154,  154,  135,  151,
      149,  147,    0,  152,    0,  149,  156,  156,    0,  157,
      157,  151,  152,    0,  150,  160,  160,    0,  155,    0,

      154,  157,    0,  151,  158,  158,  154,  157,  159,  159,
      161,  161,  158,  162,  162,    0,  156,  160,    0,  157,
      164,  164,  163,  163,  154,  160,  157,  165,  165,  162,
      163,  157,  159,    0,  158,  165,    0,  158,  159,  164,
      161,  160,    0,  162,  166,  166,  167,  167,  168,  168,
      164,    0,  163,  162,    0,  163,  159,  165,  168,    0,
      165,  179,  179,  164,  180,  180,    0,  179,    0,  181,
      181,    0,  180,    0,  166,    0,  167,    0,  168,  181,
        0,  182,  182,  168,  183,  183,  184,  184,    0,  185,
      185,  179,  179,  198,  180,  182,    0,  180,    0,  181,

      198,  198,  184,    0,  181,  188,  188,  186,  186,  187,
      187,  182,  185,    0,  183,  188,  184,    0,  186,  185,
      182,  189,  189,  187,  190,  190,  184,  191,  191,    0,
      190,    0,  192,  192,    0,  188,  185,  186,  192,  187,
      188,  193,  193,  186,    0,  189,  194,  194,  187,  195,
      195,  189,  197,  197,  190,  190,    0,  191,  223,  223,
      205,  205,  192,  192,    0,  193,    0,  196,  196,  189,
      194,  193,  206,  206,  195,    0,  194,    0,  199,  195,
      196,    0,  197,  199,  205,  199,  199,  207,  207,  193,
      205,  208,  208,    0,  194,    0,  206,  196,  195,  209,

      209,  224,  206,  224,  224,  196,  211,  211,  205,  208,
      210,  210,  212,  212,    0,  207,    0,  207,  238,  238,
      206,  208,    0,  209,  210,    0,  213,  213,    0,  209,
        0,  212,    0,  208,  214,  214,  211,  215,  215,  207,
      210,    0,  212,  216,  216,  217,  217,  209,  213,  210,
      218,  218,    0,  215,    0,  212,  213,  219,  219,    0,
      216,  220,  220,    0,  214,  226,  226,  215,  227,  227,
        0,  226,  213,  216,    0,  217,    0,  215,  227,    0,
      218,  219,  228,  228,  216,  229,  229,  219,  230,  230,
        0,  220,  231,  231,    0,  226,  226,    0,  227,  232,

      232,  233,  233,  227,    0,  219,  234,  234,  229,  235,
      235,  231,  228,  236,  236,  229,  237,  232,  230,  239,
      239,    0,  231,  237,  237,    0,  239,  236,    0,  232,
        0,  233,  229,  240,  240,  231,  234,  241,  241,  235,
        0,  232,    0,  236,  242,  242,  243,  243,    0,  239,
      246,  239,  236,  244,  244,  240,    0,  246,  246,  247,
      247,    0,  242,  240,  248,  248,  246,  241,  249,  249,
        0,  244,  250,  250,  242,  247,  243,    0,    0,  240,
      253,  253,  250,  244,  254,  254,  242,  257,  257,  247,
      253,  246,    0,    0,  248,  244,    0,    0,  249,  247,

        0,    0,  250,    0,    0,    0,    0,  250,    0,    0,
      253,  246,    0,    0,  254,  253,    0,  257,  259,  259,
      259,  260,  260,  261,  261,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "fortran.l"
#line 2 "fortran.l"
#include <stdio.h>
#include <stdlib.h>
void yyerror(char *);
#include "y.tab.h"
#line 798 "lex.yy.c"
#line 799 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 8 "fortran.l"

#line 1018 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 259 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1126 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 9 "fortran.l"
{ printf("T_PROGRAM ");return T_PROGRAM; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 10 "fortran.l"
{printf("T_SUBROUTINE ");return T_SUBROUTINE; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 11 "fortran.l"
{printf("T_FUNCTION "); return T_FUNCTION; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 12 "fortran.l"
{printf("T_RESULT ");return T_RESULT;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 13 "fortran.l"
{printf("T_CONTAINS ");return T_RESULT;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 14 "fortran.l"
{ printf("T_END ");return T_END; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 15 "fortran.l"
{ printf("T_REAL ");return T_REAL_DATA_TYPE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 16 "fortran.l"
{ printf("T_INTEGER ");return T_INT_DATA_TYPE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 17 "fortran.l"
{ printf("T_COMPLEX ");return T_COMPLEX_DATA_TYPE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 18 "fortran.l"
{ return T_CHARACTER_DATA_TYPE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 19 "fortran.l"
{ return T_LOGICAL_DATA_TYPE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 20 "fortran.l"
{ return T_DIMENSION; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 21 "fortran.l"
{ return T_DYNAMIC; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 22 "fortran.l"
{ return T_LENGTH; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 23 "fortran.l"
{ printf("T_TYPE ");return T_TYPE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 24 "fortran.l"
{printf("T_INTENT ");return T_INTENT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 25 "fortran.l"
{printf("T_IN ");return T_IN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 26 "fortran.l"
{printf("T_OUT ");return T_OUT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 27 "fortran.l"
{ printf("T_PRINT ");return T_PRINT; };
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 28 "fortran.l"
{printf("T_IF ");return T_IF; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 29 "fortran.l"
{printf("T_THEN ");return T_THEN;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 30 "fortran.l"
{printf("T_ELSEIF ");return T_ELSEIF;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 31 "fortran.l"
{printf("T_ELSE ");return T_ELSE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 32 "fortran.l"
{ printf("T_SELECT ");return T_SELECT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 33 "fortran.l"
{printf("T_CASE ");return T_CASE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 34 "fortran.l"
{printf("T_DEFAULT ");return T_DEFAULT;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 35 "fortran.l"
{printf("T_DO ");return T_DO; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 36 "fortran.l"
{printf("T_WHILE ");return T_WHILE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 37 "fortran.l"
{printf("T_CALL ");return T_CALL;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 38 "fortran.l"
{printf("T_EXIT ");return T_EXIT;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 39 "fortran.l"
{printf("T_CYCLE ");return T_CYCLE;}
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 40 "fortran.l"
{printf("T_COMMENT ");return T_COMMENT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 41 "fortran.l"
{printf("T_SWITCH ");return T_SWITCH;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 42 "fortran.l"
{return T_NOT;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 43 "fortran.l"
{return T_AND;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 44 "fortran.l"
{return T_OR;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 45 "fortran.l"
{return T_XOR;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 46 "fortran.l"
{printf("T_BAND ");return T_BAND;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 47 "fortran.l"
{return T_BOR; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 48 "fortran.l"
{return T_BXOR; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 49 "fortran.l"
{ printf("T_OPEN_BRACKET ");return T_OPEN_PARANTHESIS; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 50 "fortran.l"
{ printf("T_CLOSE_BRACKET ");return T_CLOSE_PARANTHESIS; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 51 "fortran.l"
{ return T_EQUAL; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 52 "fortran.l"
{ return T_NOTEQUAL; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 53 "fortran.l"
{ return T_ASSIGNMENT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 54 "fortran.l"
{ printf("T_DOUBLECOLON "); return T_DOUBLECOLON; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 55 "fortran.l"
{printf("T_COLON "); return T_COLON; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 56 "fortran.l"
{printf("T_ASTERISK "); return T_ASTERISK;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 57 "fortran.l"
{ printf("T_COMMA ");return T_COMMA;}
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 58 "fortran.l"
{ printf("T_ENDLINE ");return T_NEWLINE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 59 "fortran.l"
{printf ("T_SEP ");}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 60 "fortran.l"
{ return T_EXPONENT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 61 "fortran.l"
{ return T_PLUS; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 62 "fortran.l"
{ return T_MINUS; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 63 "fortran.l"
{ return T_PERCENTAGE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 64 "fortran.l"
{ return T_DIVISION; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 65 "fortran.l"
{ return T_LESS_THAN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 66 "fortran.l"
{ printf("T_GREATER_THAN ");return T_GREATER_THAN; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 67 "fortran.l"
{ return T_LESSEQUAL; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 68 "fortran.l"
{ return T_GREATEQUAL; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 69 "fortran.l"
{ return T_LOGICAL_VAL; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 70 "fortran.l"
{ return T_LOGICAL_VAL; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 71 "fortran.l"
{ printf("T_ID ");return T_ID; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 72 "fortran.l"
{/*INTEGER VALUE */ yylval=atoi(yytext);printf("T_INTEGER_VAL");return T_INTEGER_VAL; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 73 "fortran.l"
{/*REAL VALUE*/return T_REAL_VAL ; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 74 "fortran.l"
{/*DOUBLE VALUE*/return T_DOUBLE_VAL ;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 75 "fortran.l"
{/*DOUBLE VALUE*/return T_DOUBLE_VAL ;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 77 "fortran.l"
{/*CHARACTER(STRING) VALUE*/printf("T_CHARACTER_VALUE ");return T_CHARACTER_VAL ;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 78 "fortran.l"
{/*CHARACTER(STRING) VALUE*/printf("T_CHARACTER_VALUE ");return T_CHARACTER_VAL ;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 80 "fortran.l"
{/*COMPLEX VALUE*/return T_COMPLEX_VAL ;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 81 "fortran.l"
{/*COMPLEX VALUE*/return T_COMPLEX_VAL ;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 82 "fortran.l"
{/*COMPLEX VALUE*/return T_COMPLEX_VAL ;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 83 "fortran.l"
{/*COMPLEX VALUE*/printf("T_COMPLEX ");return T_COMPLEX_VAL ;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 84 "fortran.l"
{/*COMPLEX VALUE*/return T_COMPLEX_VAL ;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 85 "fortran.l"
{/*COMPLEX VALUE*/return T_COMPLEX_VAL ;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 86 "fortran.l"
{ yyerror("invalid character"); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 87 "fortran.l"
ECHO;
	YY_BREAK
#line 1462 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 259 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 259 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 258);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 87 "fortran.l"

int yywrap(void) {
return 1;
}

